config/routes.rb
Rails.application.routes.draw do
  root 'tweets#new'
  resources :tweets do
    collection do
      get 'post'
      get 'review'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    validates :text, presence: true
    validates :text, length: {maximum: 140}
    enum review_status: [:draft, :accepted, :rejected]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :twitter_client, except: :new

  def twitter_client
    @client = Twitter::REST::Client.new do |config|
      config.consumer_key = Settings[:twitter_key]
      config.consumer_secret = Settings[:twitter_secret]
      config.access_token = Settings[:twitter_token]
      config.access_token_secret = Settings[:twitter_token_secret]
    end
  end
  
  def new
    initialize_session if session.empty?
    @drafts= Tweet.where(review_status: :draft).reject do |tw|
      (session[:posted_tweet_ids] + session[:reviewed_tweet_ids]).include?(tw.id)
    end
    @rejected = Tweet.where(review_status: :rejected)
    @tweet = Tweet.new
  rescue => e
    logger.debug(e)
  end

  def create
    if session[:post_remains] < 1
      redirect_to :root, flash: {error: "残り投稿回数がありません"}
    else
      tweet=Tweet.create(create_params)
      session[:posted_tweet_ids] << tweet.id
      session[:post_remains] -= 1
      redirect_to :root, flash:{success: "投稿：#{tweet.text}"}
    end
  end
  
  def review
    votes=params[:vote]||{}
    votes.each do |id,v|
      tweet=Tweet.find(id)
      case v
      when "accept"
        tweet.accept_value+=1
        tweet.save
        if tweet.accept_value >= Settings[:accept_threshold]
          post tweet
        end
      when "reject"
        tweet.reject_value+=1
        tweet.review_status=:rejected if tweet.reject_value >= Settings[:reject_threshold]
        tweet.save
      end
      session[:reviewed_tweet_ids] << tweet.id
    end
    session[:post_remains] += votes.length/Settings[:post_review_ratio]
    redirect_to :root, flash: {success: "レビュー完了"}
  end

  def post tweet
    status = tweet.text
    option = {}
    media = valid_url?(tweet.image)
    option.update({media_ids: @client.upload(media)}) if media
    @client.update(status, option)
    tweet.destroy
  rescue => e
    logger.debug(e)
  end

  private
  def initialize_session
    session[:post_remains] ||= Settings[:initial_post_remains]
    session[:posted_tweet_ids]||=[]
    session[:reviewed_tweet_ids]||=[]
  end
  
  def create_params
    params.require(:tweet).permit(:text, :image)
  end
  
  def valid_url?(url)
    open(url)
  rescue
    false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweet_helper.rb
module TweetHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Anonytter
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag '//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js', :async => true
    :javascript
      (adsbygoogle = window.adsbygoogle || []).push({
        google_ad_client: "ca-pub-3982699505253214",
        enable_page_level_ads: true
      });
    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-94099407-1', 'auto');
      ga('send', 'pageview');
  %body
    = yield
  .container
    %p.text-right
      作者:
      = link_to "uiro", "https://twitter.com/70_"

app/views/tweets/_form.html.erb
<%= form_for(tweet) do |f| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/_form.html.haml
= form_for @tweet, :html => { :class => "form-horizontal tweet" } do |f|
  - if @tweet.errors.any?
    #error_expl.panel.panel-danger
      .panel-heading
        %h3.panel-title
          = pluralize(@tweet.errors.count, "error")
          prohibited this tweet from being saved:
      .panel-body
        %ul
          - @tweet.errors.full_messages.each do |msg|
            %li= msg
  .form-group
    = f.label :text, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :text, :class => 'form-control'
    = f.error_span(:text)
  .form-group
    = f.label :image, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :image, :class => 'form-control'
    = f.error_span(:image)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil, :class => 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), |
        tweets_path, :class => 'btn btn-default'                     |

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/edit.html.haml
- model_class = Tweet
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/tweets/new.html.haml
.bg-success= flash[:success]
.bg-danger= flash[:error]
.container
  %h1
    %span Anonytter
    %span
      %small 査読付き匿名ツイッター
  %hr
  
  このフォームから
  = link_to "@AnonytterApp", Settings[:twitter_url]
  に投稿できます。
  
  = form_for @tweet do |f|
    .form-group
      = f.label :text, "本文"
      = f.text_area :text, class:"form-control"
    .form-group
      = f.label :image, "画像URL"
      = f.text_field :image, class:"form-control"
    = f.submit '投稿', class:"btn"
  
  残り投稿回数
  = session[:post_remains]
  
  %hr
  
  %p
    他の投稿者のツイートを
    = Settings[:post_review_ratio]
    件レビューすると残り投稿回数が増えます。
  %p
    良識に従いましょう。
  = form_tag review_tweets_path, method: 'get' do
    = submit_tag "レビュー送信", class:"btn"
    %table.table
      %tr
        %th.bg-success 承認
        %th.bg-success
        %th.bg-danger 却下
        %th.bg-danger
        %th 本文
        %th 画像
      -@drafts.shuffle[0..3].each do |tw|
        %tr
          %td.bg-success= radio_button "vote", tw.id, "accept"
          %td.bg-success= tw.accept_value.to_s + "/" + Settings[:accept_threshold].to_s
          %td.bg-danger= radio_button "vote", tw.id, "reject"
          %td.bg-danger= tw.reject_value.to_s + "/" + Settings[:reject_threshold].to_s
          %td= tw.text
          %td= link_to "■",tw.image unless tw.image.empty?

  %h2 落選ツイート
  %table.table
    %tr
      %th 本文
      %th 画像
    -@rejected.reverse.each do |tw|
      %tr
        %td= tw.text
        %td= link_to "■",tw.image unless tw.image.empty?
      

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.haml
- model_class = Tweet
.page-header
  %h1= t '.title', :default => model_class.model_name.human.titleize
%dl.dl-horizontal
  %dt
    %strong
      = model_class.human_attribute_name(:text)
      \:
  %dd= @tweet.text
  %dt
    %strong
      = model_class.human_attribute_name(:image)
      \:
  %dd= @tweet.image
= link_to t('.back', :default => t("helpers.links.back")), |
  tweets_path, :class => 'btn btn-default'                 |
= link_to t('.edit', :default => t("helpers.links.edit")), |
  edit_tweet_path(@tweet), :class => 'btn btn-default'     |
= link_to t('.destroy', :default => t("helpers.links.destroy")),                                               |
  tweet_path(@tweet),                                                                                          |
  :method => 'delete',                                                                                         |
  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, |
  :class => 'btn btn-danger'                                                                                   |